spring:
  liquibase:
    enabled: true
  application:
    name: rest-api
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/library
  jpa:
    hibernate:
      ddl-auto: validate

