spring:
  application:
    name: rest-api
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Reserved2003
    url: jdbc:postgresql://localhost:5432/library
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
