spring:
  liquibase:
    enabled: true
  application:
    name: rest-api
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Reserved2003
    url: jdbc:postgresql://localhost:5432/library
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    username: user
    password: password
    host: localhost
    port: 5672
    connection-timeout: 15s

cloudinary:
  cloud_name: dbkgbcqcf
  api_key: 463961816584397
  api_secret: VXmTJHTHnvMvW3zg9VsgD0aki9w

rabbitmq:
  mailQueue:
    name: mail.queue